/*---------------------------------------------------------------------------------

	QWTF Lite Port input code
	-- generated by Maniac Xena
	-- QWTF is Team Fortress Software's property
	-- based on cquake project source code
---------------------------------------------------------------------------------*/

#include <input.h>
#include <stdio.h>

int processInput( void ) {
	scanKeys(); // scan key states
	// process key input
	

	// get touch Data
	touchPosition touch;
	touchRead(&touch);
	// process touch Data
	iprintf("\x1b[10;0HTouch x = %04i, %04i\n", touch.rawx, touch.px);
	iprintf("Touch y = %04i, %04i\n", touch.rawy, touch.py);
	return 0;
}